### ISSUE TITLE
change in FB API (v2.4) 

### ISSUE THREAD

**Issue by davidverbustel** [lewagon/rails-boilerplates#1]
there is a change in FB API (v2.4) so the lecture “Facebook connect” will not work.

In config/initializers/devise.rb the line 
> config.omniauth :facebook, "app id", "app secret", scope: 'email'

must be now  

> config.omniauth :facebook, "app id", "app secret", scope: 'email', info_fields: ‘email’

**Comment by ssaunier** [comment]
Fixed in Karr.
